name: Pull request

on: pull_request

jobs:
  build_lint_test:
    name: Build, lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get Commit Message
        run: |
          MSG=$(git log --format=%B -n 1 ${{github.event.after}})
          echo "::set-env name=COMMIT_MESSAGE::${MSG}"
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
        if: |
          !contains(env.COMMIT_MESSAGE, '[ci skip]') &&
          !contains(env.COMMIT_MESSAGE, '[skip ci]')
      - name: Yarn cache
        uses: c-hive/gha-yarn-cache@v1
        if: |
          !contains(env.COMMIT_MESSAGE, '[ci skip]') &&
          !contains(env.COMMIT_MESSAGE, '[skip ci]')
      - name: Build, lint and test
        run: |
          yarn
          yarn lint
          yarn test
          yarn dist
        if: |
          !contains(env.COMMIT_MESSAGE, '[ci skip]') &&
          !contains(env.COMMIT_MESSAGE, '[skip ci]')
